# Motivation

Why is knowing about a change of basis useful? It is useful in understanding patterns with decompositions; eigendecomposition in particular.

# Standard Unit Basis

A vector $x = \begin{bmatrix} 3 \\ 2 \end{bmatrix}$ can be visualized as a point on the 2D plane. This point is 3 units along the positive x-axis (right) and 2 units along the positive y-axis (up).

In other words, implicitly, the basis vectors for $x = \begin{bmatrix} 3 \\ 2 \end{bmatrix}$ are
\begin{align}
    \hat{i} &= \begin{bmatrix} 1 \\ 0 \end{bmatrix} \\
    \hat{j} &= \begin{bmatrix} 0 \\ 1 \end{bmatrix}
\end{align}

Here, $\hat{i}$ and $\hat{j}$ are called the **standard unit vectors** because they are used implicitly and by default. **unit** because both vectors have magnitudes 1.

To denote a basis of the standard unit vectors, we write
$$
    B = \left\{ \hat{i}, \hat{j} \right\} = \left\{ \begin{bmatrix} 1 \\ 0 \end{bmatrix}, \begin{bmatrix} 0 \\ 1 \end{bmatrix} \right\}
$$

$B$ is the **standard unit basis** in $\mathbb{R}^{2}$.

We write $ x = \begin{bmatrix} 3 \\ 2 \end{bmatrix}_{B} $ to explicitly indicate the basis of the vector $x = \begin{bmatrix} 3 \\ 2 \end{bmatrix}$ as using the basis vectors $B$, but this is usually omitted for brevity.

# Dot Product as a Change of Basis

$x = \begin{bmatrix} 3 \\ 2 \end{bmatrix}$ can really be expanded to
\begin{align}
    x &= \begin{bmatrix} 3 \\ 2 \end{bmatrix}
        = 3 \hat{i} + 2 \hat{j}
        = 3 \begin{bmatrix} 1 \\ 0 \end{bmatrix} + 2 \begin{bmatrix} 0 \\ 1 \end{bmatrix}
        = \begin{bmatrix} 3 \\ 0 \end{bmatrix} + \begin{bmatrix} 0 \\ 2 \end{bmatrix}
\end{align}

The expansion can be written in terms of the matrix dot product. We can construct a matrix $A$ whose columns are the basis vectors.

\begin{align}
    A &= \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix} \\
    x &= \begin{bmatrix} 3 \\ 2 \end{bmatrix}
        = Ax = \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix} \begin{bmatrix} 3 \\ 2 \end{bmatrix}
        = 3 \begin{bmatrix} 1 \\ 0 \end{bmatrix} + 2 \begin{bmatrix} 0 \\ 1 \end{bmatrix}
\end{align}

This shows that the dot product of a matrix $A$ and a vector $x$ can be interpreted as changing the basis of vector $x$ to use the columns of $A$ as basis vectors.

How does this work in practice with a basis other than the standard unit basis $B$? Suppose we have the following arbitrary basis vectors:
$$ C = \left\{
        \hat{i} = \begin{bmatrix} 3 \\ 1 \end{bmatrix}, 
        \hat{j} = \begin{bmatrix} 2 \\ 0 \end{bmatrix} \right\} $$

Now, we can take the vector $x$ and change its basis to $C$:
\begin{align}
    x_{C} &= \begin{bmatrix} 3 \\ 2 \end{bmatrix}_{C}
        = \begin{bmatrix} 3 & 2 \\ 1 & 0 \end{bmatrix}x
        = \begin{bmatrix} 3 & 2 \\ 1 & 0 \end{bmatrix} \begin{bmatrix} 3 \\ 2 \end{bmatrix}
        = 3 \begin{bmatrix} 3 \\ 1 \end{bmatrix} + 2 \begin{bmatrix} 2 \\ 0 \end{bmatrix}
        = \begin{bmatrix} 13 \\ 3 \end{bmatrix}
        = \begin{bmatrix} 13 \\ 3 \end{bmatrix}_{B} \\
    x_{C} &= \begin{bmatrix} 3 \\ 2 \end{bmatrix}_{C}
        = \begin{bmatrix} 13 \\ 3 \end{bmatrix}_{B}
\end{align}

# Inverse as a Change of Basis

So far, we have started with a vector $x$ and computed $x_{C}$ for an arbitrary basis $C$. Suppose that we were only given the following and asked, what is $x$?

\begin{align}
    C &= \left\{
        \hat{i} = \begin{bmatrix} 3 \\ 1 \end{bmatrix}, 
        \hat{j} = \begin{bmatrix} 2 \\ 0 \end{bmatrix} \right\} \\
    x_{C} &= \begin{bmatrix} 13 \\ 3 \end{bmatrix}_{B}
\end{align}

Since we know
\begin{align}
    x_{C} &= Ax = \begin{bmatrix} \hat{i} & \hat{j} \end{bmatrix}x = \begin{bmatrix} 3 & 2 \\ 1 & 0 \end{bmatrix}x \\
    x_{C} &= \begin{bmatrix} 3 & 2 \\ 1 & 0 \end{bmatrix}x \\
    x &= \begin{bmatrix} 3 & 2 \\ 1 & 0 \end{bmatrix}^{-1}x_{C} \\
    x &= \begin{bmatrix} 3 & 2 \\ 1 & 0 \end{bmatrix}^{-1}\begin{bmatrix} 13 \\ 3 \end{bmatrix}
        = \begin{bmatrix} 3 \\ 2 \end{bmatrix} \\
    x &= \begin{bmatrix} 0 & 1 \\ \frac{1}{2} & -\frac{3}{2} \end{bmatrix} \begin{bmatrix} 13 \\ 3 \end{bmatrix} \\
        &= 13 \begin{bmatrix} 0 \\ \frac{1}{2} \end{bmatrix} + 3 \begin{bmatrix} 1 \\ -\frac{3}{2} \end{bmatrix} \\
        &= \begin{bmatrix} \left(13\right) \left(0\right) + \left(3\right)\left(1\right) \\
            \left(13\right) \left(\frac{1}{2}\right) - \left(3\right) \left(\frac{3}{2}\right) \end{bmatrix}
            = \begin{bmatrix} 3 \\ \frac{13}{2} - \frac{9}{2} \end{bmatrix}
            = \begin{bmatrix} 3 \\ \frac{4}{2} \end{bmatrix} \\
    x &= \begin{bmatrix} 3 \\ 2 \end{bmatrix} \\
    x_{C} &= \begin{bmatrix} 3 \\ 2 \end{bmatrix}_{C}
\end{align}

In [7]:
import numpy as np

x = np.array([13
             , 3])[:, np.newaxis]
A = np.array([[3, 2]
            , [1, 0]])
Ainv = np.linalg.inv(A)
print(x)
print(Ainv)
print(Ainv.dot(x))

[[13]
 [ 3]]
[[ 0.   1. ]
 [ 0.5 -1.5]]
[[3.]
 [2.]]


The above shows that given a matrix $A$, the dot product of its inverse $A^{-1}$ and a vector $x_{B}$ using the standard unit basis gives the coordinates of $x_{C}$ if the columns of $A$ were used as the basis vectors:
$$ x_{C} = A^{-1}x_{B} $$

In the above example,
$$ \begin{bmatrix} 3 \\ 2 \end{bmatrix}_{C} 
    = \begin{bmatrix} 0 & 1 \\ \frac{1}{2} & -\frac{3}{2} \end{bmatrix}
        \begin{bmatrix} 13 \\ 3 \end{bmatrix}_{B} $$

In other words, the dot product using the inverse of a matrix results in the coordinates of the same vector but using the new basis vectors.

# Changing Basis of Linear Transformations

So far, we have discussed changing the basis of a vector $x$. Suppose we have the transformation that rotates any vector by $90 \degree$:

$$ A = \begin{bmatrix} 0 & -1 \\ 1 &0 \end{bmatrix} $$

Further suppose we have a vector $x_{C} = \begin{bmatrix} 3 \\ 2 \end{bmatrix}_{C}$, and we want to rotate it by $90 \degree$. Mathematically, we want to compute $b_{C}$ given a vector $x_{C}$ whose coordinates are using the basis $C$:
$$ A_{C}x_{C} = b_{C} $$

The task is now to find $A_{C}$, which begs the question - how do we express a linear transformation in the coordinates of the basis $C$?

To do so, we try to compute $b_{C}$ in the following manner:
- Compute the vector $x_{B}$ corresponding to $x_{C}$ by changing basis.
- Then take the product with matrix $A$ to perform the linear transformation that is a $90 \degree$ rotation.
- Finally, take the dot product with the inverse to reveal the coordinates of the same linear transformation, but using the new basis vectors.

Let us first define
$$ C = \begin{bmatrix} 3 & 2 \\ 1 & 0 \end{bmatrix} $$
as the change of basis matrix.

Then we compute the corresponding $x_{B}$ by changing basis
$$ x_{C}
    = Cx
    = \begin{bmatrix} 3 & 2 \\ 1 & 0 \end{bmatrix}
        \begin{bmatrix} 3 \\ 2 \end{bmatrix}
    = x_{B}$$

Then perform the transformation $A$ on $x_{B}$
$$ Ax_{C}
    = ACx
    = \begin{bmatrix} 0 & -1 \\ 1 &0 \end{bmatrix}
        \begin{bmatrix} 3 & 2 \\ 1 & 0 \end{bmatrix}
        \begin{bmatrix} 3 \\ 2 \end{bmatrix}
    = Ax_{B} $$

Then use the inverse $C^{-1}$ to compute the coordinates if the basis of $C$ were used to express $x_{B}$.
\begin{align}
    C^{-1}Ax_{C}
        &= C^{-1}ACx
        = \begin{bmatrix} 3 & 2 \\ 1 & 0 \end{bmatrix}^{-1}
            \begin{bmatrix} 0 & -1 \\ 1 & 0 \end{bmatrix}
            \begin{bmatrix} 3 & 2 \\ 1 & 0 \end{bmatrix}
            \begin{bmatrix} 3 \\ 2 \end{bmatrix}
        = C^{-1}Ax_{B} \\
        &= b_{C}
\end{align}

We can use Python to crunch the numbers.

In [31]:
import numpy as np

# The vector whose coordinates are in C
x = np.array([3
             ,2])[:, np.newaxis]

# The change of basis matrix
C = np.array([[3, 2],
              [1, 0]])

# The transformation matrix
A = np.array([[0, -1],
              [1,  0]])

# The inverse of the change of basis matrix
Cinv = np.linalg.inv(C)

print(f"Cx =\n{np.linalg.multi_dot([C, x])}")
print(f"ACx =\n{np.linalg.multi_dot([A, C, x])}")
print(f"CinvACx =\n{np.linalg.multi_dot([Cinv, A, C, x])}")

Cx =
[[13]
 [ 3]]
ACx =
[[-3]
 [13]]
CinvACx =
[[ 13.]
 [-21.]]


From the above, we see that
$$ b_{C} = \begin{bmatrix} 13 \\ -21 \end{bmatrix} $$

The important pattern to note here is the expression
$$ C^{-1}ACx $$

We then define $A_{C}$
$$ A_{C} = C^{-1}AC $$

Intuitively, $A_{C}$ will take the coordinates of the vector $x_{C}$ change its basis to the standard unit basis $B$, apply the transformation $A$, then express the result in coordinates that use $C$.

Python can again be used to compute $A_{C}$.

In [33]:
# The transformation matrix in basis C
A_C = np.linalg.multi_dot([Cinv, A, C])
print(f"A_C =\n{np.linalg.multi_dot([Cinv, A, C])}")

A_C =
[[ 3.  2.]
 [-5. -3.]]


To conclude, we now express the $90 \degree$ rotation in basis $C$ as follows.
\begin{align}
    A_{C}x_{C} &= b_{C} \\
    \begin{bmatrix} 3 & 2 \\ -5 & -3 \end{bmatrix}
        \begin{bmatrix} 3 \\ 2 \end{bmatrix} &=
        3 \begin{bmatrix} 3 \\ -5 \end{bmatrix} + 2 \begin{bmatrix} 2 \\ -3 \end{bmatrix} =
        \begin{bmatrix} 13 \\ -21 \end{bmatrix}
\end{align}

We confirm the results of this operation by a simple dot product using Python below.

In [34]:
# The vector in basis C
x_C = np.array([3
               ,2])[:, np.newaxis]
print(f"A_C . x_C = b_C =\n{np.linalg.multi_dot([A_C, x_C])}")

A_C . x_C = b_C =
[[ 13.]
 [-21.]]


In summary, to express a linear transformation $A$ in coordinates using basis $C$, compute
$$ A_{C} = C^{-1}AC $$

# Notable Resources
https://www.youtube.com/watch?v=P2LTAUO1TdA